"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, LoaderCircle } from "lucide-react";
import { whatsappUrl } from "@/lib/contact-handoff";

export function ContactForm({ contactWhatsapp }: { contactWhatsapp: string }) {
  const [state, setState] = useState({ name:"", business:"", whatsapp:"", email:"", need:"Landing Page", message:"", website:"" });
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [id,setId]=useState("");
  const summary = `Halo ARUNA, saya ${state.name} dari ${state.business}. Kebutuhan: ${state.need}. ${state.message}`;
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...state,kind:"contact",source:"contact_page"})});const result=await response.json();if(!response.ok)throw new Error(result.error);setId(result.submissionId);}catch(err){setError(`${err instanceof Error?err.message:"Form belum dapat dikirim."} Gunakan WhatsApp sebagai alternatif.`);}finally{setBusy(false)}}
  if(id)return <div className="border border-black/20 bg-[var(--paper)] p-8 text-center" role="status"><CheckCircle2 className="mx-auto text-[var(--success)]" size={48}/><h2 className="mt-5 text-3xl font-black">Pesan tersimpan.</h2><p className="mt-3">ID submission: <strong>{id}</strong></p>{contactWhatsapp&&<a className="button mt-6" href={whatsappUrl(contactWhatsapp,`${summary}\nID submission: ${id}`)} target="_blank" rel="noreferrer">Lanjutkan di WhatsApp <ArrowRight size={17}/></a>}</div>;
  return <form onSubmit={submit} className="grid gap-5 border border-black/20 bg-[var(--paper)] p-6 md:grid-cols-2 md:p-10"><label className="label">Nama<input required className="field" value={state.name} onChange={e=>setState({...state,name:e.target.value})}/></label><label className="label">Nama bisnis<input required className="field" value={state.business} onChange={e=>setState({...state,business:e.target.value})}/></label><label className="label">WhatsApp<input required className="field" type="tel" value={state.whatsapp} onChange={e=>setState({...state,whatsapp:e.target.value})}/></label><label className="label">Email<input required className="field" type="email" value={state.email} onChange={e=>setState({...state,email:e.target.value})}/></label><label className="label md:col-span-2">Jenis kebutuhan<select className="field" value={state.need} onChange={e=>setState({...state,need:e.target.value})}>{["Landing Page","Company Profile","Custom Website","Perbaikan Website","Belum yakin"].map(x=><option key={x}>{x}</option>)}</select></label><label className="label md:col-span-2">Pesan<textarea required className="field min-h-36 resize-y" value={state.message} onChange={e=>setState({...state,message:e.target.value})}/></label><label className="hidden" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={state.website} onChange={e=>setState({...state,website:e.target.value})}/></label>{error&&<div className="md:col-span-2"><p role="alert" className="border-l-2 border-red-600 bg-red-50 p-3 text-sm text-red-800">{error}</p>{contactWhatsapp&&<a className="text-link mt-3" href={whatsappUrl(contactWhatsapp,summary)} target="_blank" rel="noreferrer">Kirim lewat WhatsApp <ArrowRight size={16}/></a>}</div>}<button className="button md:col-span-2 md:justify-self-start" disabled={busy}>{busy&&<LoaderCircle className="animate-spin" size={17}/>}Kirim kebutuhan</button></form>;
}
