"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { LoaderCircle, Pencil, Plus, RefreshCw, Trash2 } from "lucide-react";

type Resource = "leads"|"portfolio"|"services"|"pricing"|"faq"|"blog"|"availability"|"settings";
type Item = Record<string, unknown>;
type Field = { key:string; label:string; type?:"text"|"textarea"|"number"|"checkbox"|"date"|"select"; options?:string[]; required?:boolean };
const fields:Record<Resource,Field[]>={
  leads:[{key:"status",label:"Status",type:"select",options:["NEW","CONTACTED","QUALIFIED","PROPOSAL","WON","LOST"]},{key:"notes",label:"Catatan",type:"textarea"}],
  portfolio:[{key:"slug",label:"Slug",required:true},{key:"name",label:"Nama project",required:true},{key:"category",label:"Kategori",required:true},{key:"description",label:"Deskripsi",type:"textarea",required:true},{key:"problem",label:"Masalah",type:"textarea",required:true},{key:"solution",label:"Solusi",type:"textarea",required:true},{key:"published",label:"Tayang",type:"checkbox"}],
  services:[{key:"slug",label:"Slug",required:true},{key:"title",label:"Judul",required:true},{key:"group",label:"Grup",required:true},{key:"description",label:"Deskripsi",type:"textarea",required:true},{key:"published",label:"Tayang",type:"checkbox"}],
  pricing:[{key:"slug",label:"Slug",required:true},{key:"name",label:"Nama paket",required:true},{key:"priceMin",label:"Harga minimum",type:"number",required:true},{key:"priceMax",label:"Harga maksimum",type:"number"},{key:"description",label:"Deskripsi",type:"textarea",required:true},{key:"featured",label:"Unggulan",type:"checkbox"}],
  faq:[{key:"question",label:"Pertanyaan",type:"textarea",required:true},{key:"answer",label:"Jawaban",type:"textarea",required:true},{key:"category",label:"Kategori"},{key:"published",label:"Tayang",type:"checkbox"}],
  blog:[{key:"slug",label:"Slug",required:true},{key:"title",label:"Judul",required:true},{key:"excerpt",label:"Ringkasan",type:"textarea",required:true},{key:"content",label:"Isi artikel",type:"textarea",required:true},{key:"category",label:"Kategori",required:true},{key:"published",label:"Tayang",type:"checkbox"}],
  availability:[{key:"status",label:"Status",type:"select",options:["Available","Limited","Fully booked"]},{key:"slots",label:"Jumlah slot",type:"number",required:true},{key:"estimatedStart",label:"Estimasi mulai",type:"date"}],
  settings:[{key:"key",label:"Kunci",required:true},{key:"value",label:"Nilai",type:"textarea"}],
};

function titleOf(item:Item){return String(item.name||item.title||item.question||item.business||item.key||item.status||"Item")}

export function ContentManager({resource}:{resource:Resource}){
  const [items,setItems]=useState<Item[]>([]);const [configured,setConfigured]=useState(true);const [editing,setEditing]=useState<Item|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);const res=await fetch(`/api/admin/content/${resource}`);const json=await res.json();setItems(json.items||[]);setConfigured(json.configured!==false);setMessage(json.message||"");setLoading(false)},[resource]);
  useEffect(()=>{void load()},[load]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const payload:Item={...editing};for(const f of fields[resource]){const raw=fd.get(f.key);payload[f.key]=f.type==="checkbox"?raw==="on":f.type==="number"?(raw===""?null:Number(raw)):raw===""&&f.type==="date"?null:raw}const res=await fetch(`/api/admin/content/${resource}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const json=await res.json();if(!res.ok){setMessage(json.message||"Gagal menyimpan");return}setEditing(null);setMessage("Perubahan tersimpan.");await load()}
  async function remove(id:string){if(!confirm("Hapus item ini? Tindakan tidak dapat dibatalkan."))return;const res=await fetch(`/api/admin/content/${resource}?id=${id}`,{method:"DELETE"});if(res.ok)await load();else setMessage("Item belum dapat dihapus.")}
  return <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="bg-white p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold capitalize">{resource}</h2><button className="grid size-11 place-items-center border border-black/15" aria-label="Muat ulang" onClick={()=>void load()}><RefreshCw size={17}/></button></div>{loading?<LoaderCircle className="mx-auto my-20 animate-spin"/>:!configured?<p className="border border-dashed border-black/20 p-5 text-[var(--muted)]">{message}</p>:items.length===0?<p className="py-16 text-center text-[var(--muted)]">Belum ada data.</p>:<div className="grid gap-2">{items.map(item=><div className="flex items-center gap-3 border border-black/10 p-4" key={String(item.id||item.key)}><div className="min-w-0 flex-1"><p className="truncate font-bold">{titleOf(item)}</p><p className="truncate text-xs text-[var(--muted)]">{String(item.slug||item.email||item.category||item.updatedAt||"")}</p></div><button className="grid size-10 place-items-center" aria-label={`Edit ${titleOf(item)}`} onClick={()=>setEditing(item)}><Pencil size={16}/></button>{!["leads","availability","settings"].includes(resource)&&<button className="grid size-10 place-items-center text-red-700" aria-label={`Hapus ${titleOf(item)}`} onClick={()=>void remove(String(item.id))}><Trash2 size={16}/></button>}</div>)}</div>}</section><section className="bg-white p-6"><h2 className="mb-6 flex items-center gap-2 text-xl font-bold">{editing?<><Pencil size={18}/> Edit data</>:<><Plus size={18}/> Tambah data</>}</h2>{message&&<p role="status" className="mb-5 border-l-2 border-[#f05237] bg-[var(--canvas)] p-3 text-sm">{message}</p>}<form className="grid gap-4" onSubmit={save}>{fields[resource].map(f=>f.type==="checkbox"?<label className="flex min-h-11 items-center gap-3 font-bold" key={f.key}><input name={f.key} type="checkbox" defaultChecked={Boolean(editing?.[f.key])}/>{f.label}</label>:f.type==="textarea"?<label className="label" key={f.key}>{f.label}<textarea className="field min-h-24 resize-y" name={f.key} required={f.required} defaultValue={String(editing?.[f.key]||"")}/></label>:f.type==="select"?<label className="label" key={f.key}>{f.label}<select className="field" name={f.key} defaultValue={String(editing?.[f.key]||f.options?.[0])}>{f.options?.map(x=><option key={x}>{x}</option>)}</select></label>:<label className="label" key={f.key}>{f.label}<input className="field" name={f.key} type={f.type||"text"} required={f.required} defaultValue={String(editing?.[f.key]??"")}/></label>)}<div className="flex gap-3"><button className="button" disabled={!configured}>Simpan</button>{editing&&<button type="button" className="button secondary" onClick={()=>setEditing(null)}>Batal</button>}</div></form></section></div>
}
