"use client";

import Link from "next/link";
import { ArrowRight, CalendarClock, Check, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { rupiah } from "@/lib/utils";
import { siteConfig } from "@/lib/site-config";
import type { PublicAvailability } from "@/lib/content-data";

const basePrices: Record<string, number> = { "Landing Page": 400000, "Company Profile": 900000, "E-commerce": 2200000, Booking: 1800000, Custom: 2500000 };
const featurePrices: Record<string, number> = { CMS: 300000, WhatsApp: 0, "Form Kontak": 100000, Booking: 500000, Payment: 700000, "Toko Online": 900000, Dashboard: 1000000, SEO: 300000, Blog: 400000, Multibahasa: 500000, Animasi: 250000, AI: 900000, Otomasi: 700000, API: 600000 };

function Calculator() {
  const [type, setType] = useState("Company Profile");
  const [pages, setPages] = useState(5);
  const [features, setFeatures] = useState<string[]>(["WhatsApp", "CMS"]);
  const total = useMemo(() => basePrices[type] + Math.max(0, pages - 1) * 80000 + features.reduce((sum, f) => sum + featurePrices[f], 0), [type,pages,features]);
  const toggle = (f:string) => setFeatures(v => v.includes(f) ? v.filter(x=>x!==f) : [...v,f]);
  const brief = new URLSearchParams({ type, pages:String(pages), features:features.join(","), estimate:String(total) }).toString();
  return <div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]">
    <div><label className="label">Jenis website<select className="field" value={type} onChange={e=>setType(e.target.value)}>{Object.keys(basePrices).map(x=><option key={x}>{x}</option>)}</select></label><label className="label mt-6">Jumlah halaman: <strong>{pages}</strong><input className="accent-[#f05237]" type="range" min="1" max="15" value={pages} onChange={e=>setPages(Number(e.target.value))}/></label><fieldset className="mt-7"><legend className="mb-3 text-sm font-bold">Fitur yang dibutuhkan</legend><div className="flex flex-wrap gap-2">{Object.keys(featurePrices).map(f=><button type="button" onClick={()=>toggle(f)} key={f} aria-pressed={features.includes(f)} className={`min-h-11 border px-3 text-sm font-semibold transition-colors ${features.includes(f) ? "border-[#f05237] bg-[var(--accent)] text-white":"border-black/20 bg-white"}`}>{f}</button>)}</div></fieldset></div>
    <aside className="bg-[var(--ink)] p-7 text-white md:p-9"><p className="text-sm text-white/60">Estimasi investasi</p><p className="mt-3 font-display text-4xl md:text-5xl">{rupiah(total)}</p><p className="mt-4 text-sm text-white/65">Estimasi untuk {type.toLowerCase()}, {pages} halaman, dengan kompleksitas {total > 2500000 ? "tinggi" : total > 1200000 ? "menengah" : "ringan"}.</p><Link href={`/mulai-project?${brief}`} className="button light mt-8 w-full">Mulai dengan estimasi ini <ArrowRight size={17}/></Link><p className="mt-4 text-xs text-white/45">Angka ini belum merupakan quotation final.</p></aside>
  </div>;
}

function Simulator() {
  const [name,setName] = useState("Kopi Pagi"); const [kind,setKind] = useState("Coffee shop lokal"); const [headline,setHeadline] = useState("Secangkir jeda, dekat dari rumah."); const [accent,setAccent] = useState("#9E4936");
  return <div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div className="grid content-start gap-4"><label className="label">Nama bisnis<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label className="label">Jenis bisnis<input className="field" value={kind} onChange={e=>setKind(e.target.value)}/></label><label className="label">Headline<input className="field" value={headline} onChange={e=>setHeadline(e.target.value)}/></label><label className="label">Warna utama<input className="h-12 w-full cursor-pointer bg-transparent" type="color" value={accent} onChange={e=>setAccent(e.target.value)}/></label></div><div className="overflow-hidden border border-black/15 bg-white shadow-[0_30px_80px_rgba(76,47,31,.12)]"><div className="flex h-8 items-center gap-1.5 bg-[#ece8e4] px-3"><i className="size-2 rounded-full bg-[var(--accent)]"/><i className="size-2 rounded-full bg-[#e6b45f]"/></div><div className="min-h-[430px] bg-[#fffaf2] p-7 md:p-10"><nav className="flex items-center justify-between text-xs font-black uppercase tracking-[.12em]"><span>{name || "Nama Bisnis"}</span><span>Tentang&nbsp;&nbsp; Layanan&nbsp;&nbsp; Kontak</span></nav><div className="grid min-h-[330px] content-center md:grid-cols-[1fr_.7fr] md:gap-8"><div><p className="mb-3 text-xs font-bold uppercase tracking-widest" style={{color:accent}}>{kind || "Jenis bisnis"}</p><h3 className="font-display text-4xl leading-[.95] tracking-[-.04em] md:text-5xl">{headline || "Headline bisnis Anda"}</h3><button className="mt-7 px-4 py-2 text-sm font-bold text-white" style={{background:accent}}>Hubungi Kami</button></div><div className="mt-8 min-h-44 rounded-[50%_50%_8px_8px] md:mt-0" style={{background:accent}}/></div></div></div></div>;
}

function Estimator() {
  const [input,setInput] = useState(""); const [result,setResult] = useState<{type:string;features:string[];price:string}|null>(null);
  function estimate(){ const q=input.toLowerCase(); const commerce=/toko|produk|jual|payment/.test(q); const booking=/booking|reservasi|jadwal/.test(q); const features=[q.includes("whatsapp")?"WhatsApp":null,booking?"Booking":null,commerce?"Katalog & pembayaran":null,q.includes("blog")?"Blog":null,"SEO dasar"].filter(Boolean) as string[]; setResult({type:commerce?"E-commerce":booking?"Website Booking":"Company Profile",features,price:commerce?"Rp2,2-4,5 juta":booking?"Rp1,8-3 juta":"Rp900 ribu-1,4 juta"}); }
  return <div className="grid gap-7 md:grid-cols-[1fr_.8fr]"><div><label className="label">Ceritakan kebutuhan Anda<textarea rows={6} className="field resize-y" value={input} onChange={e=>setInput(e.target.value)} placeholder="Contoh: Saya punya bengkel dan mau website dengan daftar layanan, WhatsApp, booking servis, dan lokasi..."/></label><button className="button mt-4" onClick={estimate} disabled={!input.trim()}><Sparkles size={17}/> Buat estimasi</button></div><aside className="min-h-64 border border-black/15 bg-white p-7">{result ? <div><p className="mb-2 text-xs font-bold uppercase tracking-[.12em]">Rekomendasi</p><h3 className="font-display text-3xl">{result.type}</h3><p className="mt-3 text-xl font-black text-[var(--accent)]">{result.price}</p><ul className="mt-5 grid gap-2">{result.features.map(f=><li key={f} className="flex items-center gap-2"><Check size={16}/>{f}</li>)}</ul><p className="mt-5 text-xs text-[var(--muted)]">Estimator menggunakan fallback berbasis kebutuhan. Hasil final dikonfirmasi saat konsultasi.</p></div>:<div className="grid h-full place-content-center text-center text-[#8a817b]"><Sparkles className="mx-auto mb-3"/><p>Rekomendasi akan muncul di sini.</p></div>}</aside></div>;
}

export function InteractiveStudio({ initialAvailability = siteConfig.availability }: { initialAvailability?: PublicAvailability }) {
  const [tab,setTab] = useState<"harga"|"simulasi"|"ai">("harga");
  const availability = initialAvailability;
  return <section className="section bg-[var(--paper)]" id="studio"><div className="container"><div className="mb-12 max-w-4xl"><h2 className="heading">Coba sebelum mulai.</h2><p className="subheading mb-0 mt-6">Hitung biaya, buat preview sederhana, atau tulis kebutuhan Anda dengan bahasa sehari-hari.</p></div><div className="mb-8 flex gap-2 overflow-x-auto pb-2" role="tablist" aria-label="Alat perencanaan"><button role="tab" aria-selected={tab==="harga"} className={`button whitespace-nowrap ${tab!=="harga"?"secondary":""}`} onClick={()=>setTab("harga")}>Hitung Harga</button><button role="tab" aria-selected={tab==="simulasi"} className={`button whitespace-nowrap ${tab!=="simulasi"?"secondary":""}`} onClick={()=>setTab("simulasi")}>Simulasi Website</button><button role="tab" aria-selected={tab==="ai"} className={`button whitespace-nowrap ${tab!=="ai"?"secondary":""}`} onClick={()=>setTab("ai")}>AI Estimator</button></div><div className="border border-black/20 bg-[var(--canvas)] p-5 md:p-9">{tab==="harga"?<Calculator/>:tab==="simulasi"?<Simulator/>:<Estimator/>}</div><div className="mt-6 flex items-center gap-3 border border-black/20 bg-[var(--surface)] px-5 py-4"><CalendarClock className="shrink-0 text-[var(--accent)]"/><p><strong>Slot project saat ini: {availability.status.toLowerCase()}.</strong> {availability.message}</p></div></div></section>;
}
